### ISSUE TITLE
тло звучить набагато краще ніж фоновий колір.

### ISSUE THREAD

**Issue by malytskyy** [vscode-ukrainian/translation#1]
в режимі тестування, давайте визначимось

**Comment by borysl** [comment]
Мені здається спочатку треба збілдити vscode і подивитися як воно буде в середовищи

**Comment by malytskyy** [comment]
@borysl ми вже майже досягнули 35%, так що можемо зробити запит. Як на мене, головне використовувати те саме слово\вираз, щоб потім знайти при потребі. Навіть як буде білд для нас, все можливі контексти продивитись буде важко чи навіть неможливо
